http {
    server {
        listen 2999;
        root /home/hyuze/kerjaan/maintenis/maintenis.tech;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
